############################
## CHANGE THESE
############################

baseURL: 'https://common-again.github.io/Qubt-testevhnn'
title: Qubt-testevhnn

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


